backend:
  name: git-gateway
  branch: main
local_backend: false

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/assets/blogs"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "type", label: "Type", widget: "select", options: ["tutorial", "guide", "case-study", "opinion"] }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "readTime", label: "Read Time", widget: "string" }
      - { name: "thumbnail", label: "Thumbnail Image", widget: "image" }
      - { name: "viewCount", label: "View Count", widget: "number", default: 0 }
      - { name: "likeCount", label: "Like Count", widget: "number", default: 0 }
      - { name: "tags", label: "Tags", widget: "list", default: [] }

      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - { name: "name", label: "Name", widget: "string" }
          - { name: "avatar", label: "Avatar", widget: "image" }
          - { name: "designation", label: "Designation", widget: "string" }
          - { name: "company", label: "Company", widget: "string", required: false }
          - { name: "companyLink", label: "Company Link", widget: "string", required: false }

      - { name: "body", label: "Body", widget: "markdown" }
